/// Core models, enums, interfaces, and merge engine for health_forge.
library;

// Enums
export 'src/enums/access_mode.dart';
export 'src/enums/conflict_strategy.dart';
export 'src/enums/data_origin.dart';
export 'src/enums/data_provider.dart';
export 'src/enums/freshness.dart';
export 'src/enums/metric_type.dart';
export 'src/enums/sync_model.dart';
// Interfaces
export 'src/interfaces/auth_result.dart';
export 'src/interfaces/auth_status.dart';
export 'src/interfaces/health_provider.dart';
export 'src/interfaces/provider_capability.dart';
// Merge
export 'src/merge/duplicate_detector.dart';
export 'src/merge/merge_config.dart';
export 'src/merge/merge_engine.dart';
export 'src/merge/merge_result.dart';
export 'src/merge/strategies/average_strategy.dart';
export 'src/merge/strategies/conflict_strategy_handler.dart';
export 'src/merge/strategies/custom_strategy.dart';
export 'src/merge/strategies/keep_all_with_attribution.dart';
export 'src/merge/strategies/most_granular.dart';
export 'src/merge/strategies/priority_based.dart';
// Models
export 'src/models/activity/activity_session.dart';
export 'src/models/activity/calories_burned.dart';
export 'src/models/activity/distance_sample.dart';
export 'src/models/activity/elevation_gain.dart';
export 'src/models/activity/step_count.dart';
export 'src/models/activity/workout_route.dart';
export 'src/models/body/blood_glucose.dart';
export 'src/models/body/blood_pressure.dart';
export 'src/models/body/body_fat.dart';
export 'src/models/body/weight.dart';
export 'src/models/cardiovascular/heart_rate_sample.dart';
export 'src/models/cardiovascular/heart_rate_variability.dart';
export 'src/models/cardiovascular/resting_heart_rate.dart';
export 'src/models/device_info.dart';
export 'src/models/extensions/garmin_sleep_extension.dart';
export 'src/models/extensions/oura_sleep_extension.dart';
export 'src/models/extensions/provider_extension_registry.dart';
export 'src/models/extensions/strava_workout_extension.dart';
export 'src/models/health_record.dart';
export 'src/models/provenance.dart';
export 'src/models/provider_extension.dart';
export 'src/models/recovery/readiness_score.dart';
export 'src/models/recovery/recovery_metric.dart';
export 'src/models/recovery/stress_score.dart';
export 'src/models/respiratory/blood_oxygen_sample.dart';
export 'src/models/respiratory/respiratory_rate.dart';
export 'src/models/sleep/sleep_score.dart';
export 'src/models/sleep/sleep_session.dart';
export 'src/models/sleep/sleep_stage_segment.dart';
export 'src/models/time_range.dart';
// Serialization
export 'src/serialization/json_converters.dart';
// Util
export 'src/util/id_generator.dart';
