name: health_forge_garmin
description: Garmin adapter for health_forge (experimental)
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

resolution: workspace

dependencies:
  dio: ^5.11.1
  flutter:
    sdk: flutter
  health_forge_core:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  very_good_analysis: ^11.0.0
